# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166qPHnIWejDcyO2ER0xexH8xn_983V5h
"""

import pandas as pd

dataset = pd.read_csv('dataset_ajuste.csv')

print(dataset.head())
print(dataset.info())
print(dataset.shape)
print(dataset.info)

from pyproj import CRS, Transformer

crs_3949 = CRS('EPSG:3949')
crs_latlon = CRS('EPSG:4326')

transformer = Transformer.from_crs(crs_3949, crs_latlon, always_xy=True)
longitudes, latitudes = transformer.transform(dataset['X'].values, dataset['Y'].values)

dataset['longitude'] = longitudes
dataset['latitude'] = latitudes

print("Dataset avec les nouvelles colonnes latitude et longitude:")
display(dataset[['X', 'Y', 'latitude', 'longitude']].head())

from plotly import data
import plotly.express as px
import plotly.graph_objects as go

choix_init = input("souhaitez vous savoir à quel cluster appartient un arbre ou voir la carte qui répertorie les arbres ? Tapez 1 pour l'arbre, tapez 2 pour la carte.")

while choix_init != "1" and choix_init != "2":
  print("choix non valide. Choix possibles : 1 et 2")
  choix_init = input("souhaitez vous savoir à quel cluster appartient un arbre ou voir la carte qui répertorie les arbres ? Tapez 1 pour l'arbre, tapez 2 pour la carte.")

if choix_init == "1":
  choix_nb_cluster = input("Combien de cluster voulez-vous ? choix possible : 2 ou 3")
  while choix_nb_cluster != "2" and choix_nb_cluster != "3":
    print("choix non valide. Choix possibles : 2 et 3 ")
    choix_nb_cluster = input("Combien de cluster voulez-vous ? choix possible : 2 ou 3")

  choix_taille = input("Quel taille d'arbre souhaitez-vous catégoriser ? ")
  choix_taille_num = float(choix_taille)

  trouve = False

  for i in range(len(dataset)):

    if dataset.loc[i, 'haut_tot'] == choix_taille_num:
        trouve = True
        if choix_nb_cluster == "3":
          if dataset.loc[i, 'cluster_taille3'] == "petit":
            print("cet arbre est petit")
            break
          elif dataset.loc[i, 'cluster_taille3'] == "moyen":
            print("cet arbre est moyen")
            break
          elif dataset.loc[i, 'cluster_taille3'] == "grand":
            print("cet arbre est grand")
            break
        elif choix_nb_cluster == "2":
          if dataset.loc[i, 'cluster_taille2'] == "petit":
            print("cet arbre est petit")
            break

          elif dataset.loc[i, 'cluster_taille2'] == "grand":
            print("cet arbre est grand")
            break

  if not trouve:
      print("Aucun arbre trouvé avec cette taille.")


elif choix_init=="2":
  choix_nb_cluster = input("Préférez-vous voir 2 ou 3 cluster ? ")
  while choix_nb_cluster != "2" and choix_nb_cluster != "3":
    print("choix non valide. Choix possibles : 2 et 3 ")
    choix_nb_cluster = input("Combien de cluster voulez-vous ? choix possible : 2 ou 3")
  if choix_nb_cluster =="2":
    map_x2 = dataset.merge(dataset[['cluster_taille2']], left_index=True, right_index=True, how='left')
    fig = px.scatter_map(dataset, lat='latitude', lon='longitude', color = 'cluster_taille2', zoom=12)
    fig.show()
  elif choix_nb_cluster =="3":
    map_x3 = dataset.merge(dataset[['cluster_taille3']], left_index=True, right_index=True, how='left')
    fig = px.scatter_map(dataset, lat='latitude', lon='longitude', color = 'cluster_taille3', zoom=12)
    fig.show()