# -*- coding: utf-8 -*-
"""script_python_projet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166qPHnIWejDcyO2ER0xexH8xn_983V5h
"""

########## import des bibliothèques et lecture du dataset ###########

from pyproj import CRS, Transformer
import pandas as pd
from plotly import data
import plotly.express as px
import plotly.graph_objects as go

from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_csv('/content/drive/MyDrive/TP_IA/dataset_ajuste.csv')

print(dataset.head())
print(dataset.info())
print(dataset.shape)
print(dataset.info)

############# conversion des coordonnées référence spatial en coordonnées latitude et longitude #############

#crs 3949 trouvé lors de recherche sur le dataset, mesure prise par rapport à cette référence
#crs 4326 est la référence internationale pour les latitudes et longitudes GPS
crs_3949 = CRS('EPSG:3949')
crs_latlon = CRS('EPSG:4326')

#on convertie les valeurs du dataset X et Y en coordonnées GPS
transformer = Transformer.from_crs(crs_3949, crs_latlon, always_xy=True)
longitudes, latitudes = transformer.transform(dataset['X'].values, dataset['Y'].values)

#on attribue au nouvelles lignes les nouvelles coordonnées
dataset['longitude'] = longitudes
dataset['latitude'] = latitudes

#afficher un tableau résumé comparatif entre les anciennes et les nouvelles coordonnées

print("Dataset avec les nouvelles colonnes latitude et longitude:")
display(dataset[['X', 'Y', 'latitude', 'longitude']].head())

############ interaction avec l'utilisateur ##############

#on initialise une variable qui va retenir le choix du client entre voir à quelle catégorie appartient un arbre ou voir la carte
choix_init = input("souhaitez vous savoir à quel cluster appartient un arbre ou voir la carte qui répertorie les arbres ?\n Tapez 1 pour l'arbre, tapez 2 pour la carte.")

#si le choix n'est pas dans les options on demande au client de mettre un choix valide jusqu'à ce qu'il le fasse
while choix_init != "1" and choix_init != "2":
  print("choix non valide. Choix possibles : 1 et 2")
  choix_init = input("souhaitez vous savoir à quel cluster appartient un arbre ou voir la carte qui répertorie les arbres ?\n Tapez 1 pour l'arbre, tapez 2 pour la carte.")

#on demande au client s'il préfère avoir 2 catégories ou 3
if choix_init == "1":
  choix_nb_cluster = input("Combien de catégories souhaitez-vous?,\n choix possible : 2 ou 3")

  #si le choix n'est pas dans les options on demande au client de mettre un choix valide jusqu'à ce qu'il le fasse
  while choix_nb_cluster != "2" and choix_nb_cluster != "3":
    print("choix non valide. Choix possibles : 2 et 3 ")
    choix_nb_cluster = input("Combien de cluster voulez-vous ?\n choix possible : 2 ou 3")

  #on demande au client quelle est la taille qu'il souhaite catégoriser pour savoir à quel catégorie appartient un arbre de x mètre
  choix_taille = input("Quel taille d'arbre souhaitez-vous catégoriser ?\n entrez un entier naturel.")
  choix_taille_num = float(choix_taille)

  #on initialise une variable pour savoir pendant la boucle si on trouve la taille de l'arbre

  trouve = False

  #on fait une boucle qui parcourt le tableau et compare pour savoir si un arbre fait la taille demandée et sa catégorie

  for i in range(len(dataset)):

    if dataset.loc[i, 'haut_tot'] == choix_taille_num:
        trouve = True
        if choix_nb_cluster == "3":
          if dataset.loc[i, 'cluster_taille3'] == "petit":
            print("cet arbre est petit")
            break
          elif dataset.loc[i, 'cluster_taille3'] == "moyen":
            print("cet arbre est moyen")
            break
          elif dataset.loc[i, 'cluster_taille3'] == "grand":
            print("cet arbre est grand")
            break
        elif choix_nb_cluster == "2":
          if dataset.loc[i, 'cluster_taille2'] == "petit":
            print("cet arbre est petit")
            break

          elif dataset.loc[i, 'cluster_taille2'] == "grand":
            print("cet arbre est grand")
            break

  if not trouve:
    if choix_nb_cluster == "3":
      if choix_taille_num > 18:
        print("ce nouvel arbre est grand")
      if choix_taille_num < 11:
        print("cet arbre est petit")
      else:
        print("ce nouvel arbre est moyen")

    elif choix_nb_cluster == "2":
      if choix_taille_num > 11:
        print("ce nouvel arbre est grand")
      else:
        print("ce nouvel arbre est petit")
#on créer la carte intéractive en fonction du nombre de catégorie demandée

elif choix_init=="2":
  choix_nb_cluster = input("Préférez-vous voir 2 ou 3 cluster ?\n choix possible : 2 ou 3 ")
  while choix_nb_cluster != "2" and choix_nb_cluster != "3":
    print("choix non valide.","\n", "Choix possibles : 2 et 3 ")
    choix_nb_cluster = input("Combien de cluster voulez-vous ?\n choix possible : 2 ou 3")
  if choix_nb_cluster =="2":
    map_x2 = dataset.merge(dataset[['cluster_taille2']], left_index=True, right_index=True, how='left')
    fig = px.scatter_map(dataset, lat='latitude', lon='longitude', color = 'cluster_taille2', hover_data=['remarquable','nomfrancais','fk_pied','clc_quartier','clc_secteur','haut_tronc','tronc_diam','fk_stadedev','fk_port','fk_revetement','feuillage','fk_situation'], zoom=12)
    fig.show()
  elif choix_nb_cluster =="3":
    map_x3 = dataset.merge(dataset[['cluster_taille3']], left_index=True, right_index=True, how='left')
    fig = px.scatter_map(dataset, lat='latitude', lon='longitude', color = 'cluster_taille3', hover_data=['remarquable','nomfrancais','fk_pied','clc_quartier','clc_secteur','haut_tronc','tronc_diam','fk_stadedev','fk_port','fk_revetement','feuillage','fk_situation'], zoom=12)
    fig.show()
